<?php

namespace Database\Seeders;

use App\Models\Barang;
use App\Models\BarangToko;
use App\Models\Toko;
use Illuminate\Database\Seeder;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [1, 'ADAPTOR 12V 1A'],
            [2, 'AETHERCOM ADAPTER SC UPC'],
            [3, 'BOX ODP HITAM 8 CORE'],
            [4, 'BOX ODP HITAM X6'],
            [5, 'BOX ODP PUTIH 16 CORE DL'],
            [6, 'BOX ODP PUTIH 16 CORE SL'],
            [7, 'BOX ODP PUTIH 8 CORE'],
            [8, 'ECONOMIS ADAPTOR 12V 1A'],
            [9, 'ECONOMIS PATCHCORE FLAT 1.5M'],
            [10, 'ECONOMIS PATCHCORE FLAT 10M'],
            [11, 'ECONOMIS PATCHCORE FLAT 1M'],
            [12, 'ECONOMIS PATCHCORE FLAT 20M'],
            [13, 'ECONOMIS PATCHCORE FLAT 2M'],
            [14, 'ECONOMIS PATCHCORE FLAT 3M'],
            [15, 'ECONOMIS PATCHCORE FLAT 5M'],
            [16, 'FUJI ADAPTER SC  UPC'],
            [17, 'FUJI CLEAVER FM06'],
            [18, 'FUJI KABEL FO 1 CORE'],
            [19, 'FUJI PATCHORE BIRU 3M 2MM'],
            [20, 'FUJI PATCHORE HITAM 1M 2MM'],
            [21, 'FUJI PATCHORE HITAM 1M 3MM'],
            [22, 'FUJI PATCHORE HITAM 2M 2MM'],
            [23, 'FUJI PATCHORE HITAM 2M 3MM'],
            [24, 'FUJI PATCHORE HITAM 3M 2MM'],
            [25, 'FUJI PATCHORE HITAM 3M 3MM'],
            [26, 'FUJI PATCHORE KUNING 1M 2MM'],
            [27, 'FUJI PATCHORE KUNING 1M 3MM'],
            [28, 'FUJI PATCHORE KUNING 2M 2MM'],
            [29, 'FUJI PATCHORE KUNING 2M 3MM'],
            [30, 'FUJI PATCHORE KUNING 3M 3MM'],
            [31, 'FUJI SFP EPON 10DB'],
            [32, 'FUJI SFP GPON 10DB'],
            [33, 'FUJI SPLITER BOX 1:2'],
            [34, 'FUJI SPLITER BOX 1:4'],
            [35, 'FUJI SPLITER BOX 1:8'],
            [36, 'FUJI SPLITTER BOX 1:16'],
            [37, 'FUJI TANG STRIPER'],
            [38, 'HISFOCUS ADAPTOR 12V 3A CA'],
            [39, 'HISFOCUS OLT 2P 1G'],
            [40, 'HISFOCUS OLT 4P 1G'],
            [41, 'HISFOCUS SFP 10dB EPON'],
            [42, 'HISFOCUS SFP 10dB GPON'],
            [43, 'JOIN CLOSUR 12C'],
            [44, 'JOINT CLOSUR 6C'],
            [45, 'KASET HITAM'],
            [46, 'NITTO ISOLASI'],
            [47, 'PAKE KLEM UK 6'],
            [48, 'POWERFULL OPM MULTI R270'],
            [49, 'POWERFULL PATCHORE 3M 3MM'],
            [50, 'POWERFULL SPLIT BLACK 1:2 2MM'],
            [51, 'POWERFULL SPLIT BLACK 1:2 3MM'],
            [52, 'POWERFULL SPLIT BLACK 1:4 2MM'],
            [53, 'POWERFULL SPLIT BLACK 1:8 2MM'],
            [54, 'POWERFULL SPLITBOX 1:16 HQ'],
            [55, 'POWERFULL SPLITBOX 1:2 HQ'],
            [56, 'POWERFULL SPLITBOX 1:4 HQ'],
            [57, 'POWERFULL SPLITBOX 1:8 HQ'],
            [58, 'POWERFULL VFL 15MW'],
            [59, 'PROTEK BESAR'],
            [60, 'PROTEK KECIL'],
            [61, 'RASIO 1:99'],
            [62, 'RASIO 10:90'],
            [63, 'RASIO 12:88'],
            [64, 'RASIO 15:85'],
            [65, 'RASIO 2:98'],
            [66, 'RASIO 20:80'],
            [67, 'RASIO 25:75'],
            [68, 'RASIO 3:97'],
            [69, 'RASIO 30:70'],
            [70, 'RASIO 35:65'],
            [71, 'RASIO 4:96'],
            [72, 'RASIO 40:60'],
            [73, 'RASIO 45:55'],
            [74, 'RASIO 5:95'],
            [75, 'RASIO 50:50'],
            [76, 'RASIO 6:94'],
            [77, 'RASIO 7:93'],
            [78, 'RASIO 8:92'],
            [79, 'RASIO 9:91'],
            [80, 'RING BOX ODP'],
            [81, 'ROSET 4C'],
            [82, 'ROSET 8C'],
            [83, 'SPEEDBOOST 2 JALUR - 12 ODP'],
            [84, 'SPEEDBOOST 2 JALUR - 16 ODP'],
            [85, 'SPEEDBOOST 2 ODC'],
            [86, 'SPEEDBOOST 3 ODC'],
            [87, 'SPEEDBOOST 4 JALUR - 1 JALUR'],
            [88, 'SPEEDBOOST 4 ODC'],
            [89, 'SPEEDBOOST 4 ODC - NOMOR 1'],
            [90, 'SPEEDBOOST 4 ODC - NOMOR 2 25:75'],
            [91, 'SPEEDBOOST 4 ODC - NOMOR 2 30:70'],
            [92, 'SPEEDBOOST 4 ODC - NOMOR 3'],
            [93, 'SPEEDBOOST 8 ODP'],
            [94, 'SPEEDBOOST 9 ODP'],
            [95, 'SPEEDCORE 1 CORE 3 SELING'],
            [96, 'TEKIRO TANG POTONG 6 IN'],
            [97, 'TP-LINK 840 NEW'],
            [98, 'XUMI ADAPTER SC UPC'],
            [99, 'XUMI PATCHCORE KUNING 1.5M 3MM'],
            [100, 'XUMI PATCHCORE KUNING 1M 3MM'],
            [101, 'XUMI PATCHCORE KUNING 2M 3MM'],
            [102, 'XUMI PATCHCORE KUNING 3M 2MM '],
            [103, 'XUMI PATCHCORE KUNING 3M 3MM'],
            [104, 'XUMI SPLITER BOX 1:2'],
            [105, 'XUMI SPLITER BOX 1:4'],
            [106, 'XUMI SPLITER BOX 1:8'],
            [107, 'XUMI SPLITTER BOX 1:16'],
            [108, 'XUMI TANG DROP'],
            [109, 'XUMI TANG STRIPER'],
            [110, 'XUMIKURA SFP 10dB EPON'],
            [111, 'ZTE EPON F477 V2'],
            [112, 'ZTE XPON F609E'],
            [113, 'ZTE XPON F660'],
            [114, 'Fuji Tang Drop'],
            [115, 'Spliter Rasio Box 1:8 With FBT OUT 1:99%'],
            [116, 'Spliter Rasio Box 1:8 With FBT OUT 2:98%'],
            [117, 'Spliter Rasio Box 1:8 With FBT OUT 3:97%'],
            [118, 'Spliter Rasio Box 1:8 With FBT OUT 4:96%'],
            [119, 'Spliter Rasio Box 1:8 With FBT OUT 5:95%'],
            [120, 'Spliter Rasio Box 1:8 With FBT OUT 6:94%'],
            [121, 'Spliter Rasio Box 1:8 With FBT OUT 7:93%'],
            [122, 'Spliter Rasio Box 1:8 With FBT OUT 8:92%'],
            [123, 'Spliter Rasio Box 1:8 With FBT OUT 9:91%'],
            [124, 'Spliter Rasio Box 1:8 With FBT OUT 10:90%'],
            [125, 'Spliter Rasio Box 1:8 With FBT OUT 12:88%'],
            [126, 'Spliter Rasio Box 1:8 With FBT OUT 15:85%'],
            [127, 'Spliter Rasio Box 1:8 With FBT OUT 20:80%'],
            [128, 'Spliter Rasio Box 1:8 With FBT OUT 25:75%'],
            [129, 'Spliter Rasio Box 1:8 With FBT OUT 30:70%'],
            [130, 'Spliter Rasio Box 1:8 With FBT OUT 35:65%'],
            [131, 'Spliter Rasio Box 1:8 With FBT OUT 40:60%'],
            [132, 'Spliter Rasio Box 1:8 With FBT OUT 50:50%'],
            [133, 'ECONOMIS KABEL FO 1 CORE'],
            [134, 'POWERFULL PATCHORE 1M 3MM'],
            [135, 'POWERFULL PATCHORE 1,5M 3MM'],
            [136, 'POWERFULL PATCHORE 2M 3MM'],
            [137, 'XUMI PATCHCORE HITAM 1M 2MM'],
            [138, 'XUMI PATCHCORE HITAM 1.5M 2MM'],
            [139, 'XUMI PATCHCORE KUNING 1.5M 2MM '],
            [140, 'XUMI PATCHCORE KUNING 2M 2MM '],
            [141, 'XUMI 4 CORE FIG 8'],
            [142, 'XUMI 6 CORE FIG 8'],
            [143, 'XUMI 8 CORE FIG 8'],
            [144, 'XUMI 12 CORE FIG 8'],
            [145, 'POWERFULL JELLY TUBE 2 CORE'],
            [146, 'POWERFULL JELLY TUBE 4 CORE'],
            [147, 'PAKET SPLITTER RASIO 8 ODP V1'],
            [148, 'PAKET SPLITTER RASIO 8 ODP V2'],
            [149, 'PAKET SPLITTER RASIO 8 ODP V3'],
            [150, 'PAKET SPLITTER RASIO 8 ODP V4'],
            [151, 'PAKET SPLITTER RASIO 9 ODP V1'],
            [152, 'PAKET SPLITTER RASIO 9 ODP V2'],
            [153, 'PAKET SPLITTER RASIO 9 ODP V3'],
            [154, 'PAKET SPLITTER RASIO 9 ODP V4'],
            [155, 'ZTE EPON F460'],
            [156, 'JOINT CLOSUR 24 - 48C DOME'],
            [157, 'FUJI PATCHORE BIRU 3M 3MM'],
            [158, 'FUJI PATCHORE KUNING 3M 2MM'],
            [159, 'SPEEDBOOST 8 ODP 1:2'],
            [160, 'ZTE XPON F663'],
            [161, 'TUMTEC CLEAVER A8'],
            [162, 'POWERFULL FUSION SPLICER'],
            [163, 'HISFOCUS OLT BOARD'],
            [164, 'SPEEDBOOST 2 JALUR - 12 ODP + BOX ODP PUTIH'],
            [165, 'SPEEDBOOST 2 JALUR - 12 ODP + BOX ODP HITAM'],
            [166, 'SPLITTER BOX 1:8 - KOSONGAN'],
            [167, 'SPLITTER BOX 1:4 - KOSONGAN'],
            [168, 'SPLITTER BOX 1:2 - KOSONGAN'],
            [169, 'SISTEM ESTAFET 32 CLIENT V1'],
            [170, 'SISTEM ESTAFET 32 CLIENT V2'],
            [171, 'SISTEM ESTAFET 32 CLIENT V3'],
            [172, 'SISTEM ESTAFET 32 CLIENT V4'],
            [173, 'SPEEDBOOST 9 ODP + BOX ODP PUTIH'],
            [174, 'SPEEDBOOST 9 ODP + BOX ODP HITAM'],
            [175, 'SPEEDBOOST 8 ODP + BOX ODP PUTIH'],
            [176, 'SPEEDBOOST 8 ODP + BOX ODP HITAM'],
            [177, 'SPEEDBOOST 8 ODP 1:2 + SPLITER BOX 1:8'],
            [178, 'SPEEDBOOST 8 ODP 1:2 + SPLITER BOX 1:8, ODP 16'],
            [179, 'SPEEDBOOST 2 ODC + BOX'],
            [180, 'SPEEDBOOST 3 ODC + BOX'],
            [181, 'SPEEDBOOST 4 ODC + BOX'],
            [182, 'XUMI ADAPTER FLI'],
            [183, 'ZTE EPON F477 V2 + ADAPTOR'],
            [184, 'XUMI PATCHCORE KUNING 1M 2MM '],
            [185, 'SPEEDBOOST 2 JALUR - 8 ODP '],
            [186, 'PRECON 50M'],
            [187, 'PRECON 80M'],
            [188, 'PRECON 100M'],
            [189, 'SLITTER K2'],
            [190, 'SLITTER K3'],
            [191, 'XUMIKURA SPLITTER PLC 1:2'],
            [192, 'Xumikura Pigtail 12 Color'],
            [193, 'OTDR P350'],
            [194, 'JOINT CLOSUR 48 CORE INLINE'],
        ];

        $tokoIds = Toko::pluck('id');

        foreach ($items as [$no, $nama]) {
            $kode = str_pad($no, 3, '0', STR_PAD_LEFT);
            $barang = Barang::firstOrCreate(
                ['kode_barang' => $kode],
                ['nama_barang' => $nama],
            );

            foreach ($tokoIds as $tokoId) {
                BarangToko::firstOrCreate(
                    ['barang_id' => $barang->id, 'toko_id' => $tokoId],
                    ['stok_gudang' => 0, 'stok_packing' => 0, 'total_stok' => 0, 'stock_threshold' => 0],
                );
            }
        }

        $this->command->info(count($items).' barang imported to '.$tokoIds->count().' tokos.');
    }
}
